# Generated by Django 6.0.6 on 2026-06-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_tenant_to_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='rent', max_length=10),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (optional if image file is uploaded)'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
